hello:
  msg: hollyshit

debug: false
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    username: root
    password: yd019012
    url: jdbc:mysql://192.168.229.131:3306/yspring?useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.jdbc.Driver
  thymeleaf:
    mode: LEGACYHTML5
    encoding: UTF-8
    cache: false
    prefix: classpath:/templates/
    suffix: .html
  #redis config
  redis:
  # database: 0
  # host: yonyong.top
  # port: 20200
  # password:
    # jedis:
    lettuce:
      pool:
        # 连接池中的最大空闲连接 默认8
        max-idle: 8
        # 连接池中的最小空闲连接 默认0
        min-idle: 0
        # 连接池最大连接数 默认8 ，负数表示没有限制
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认-1
        max-wait: -1
    timeout: 30000
    sentinel:
      master: mymaster
      nodes: 192.168.229.135:26379,192.168.229.135:26380,192.168.229.135:26381
logging:
  level:
    root: error

